# Generated by Django 4.0 on 2021-12-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'product category', 'verbose_name_plural': 'product categories'},
        ),
    ]
