# Generated by Django 4.0 on 2021-12-20 19:35

from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(help_text='format: required, unique', max_length=50, unique=True, verbose_name='product website ID')),
                ('name', models.CharField(help_text='format: required, max-255 characters', max_length=255, unique=True, verbose_name='product name')),
                ('slug', models.SlugField(help_text='format: required, letters, numbers, underscores or hyphens', max_length=255, verbose_name='product safe URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: y-m-d H:M:S', verbose_name='date product created')),
                ('category', mptt.fields.TreeManyToManyField(to='inventory.Category')),
            ],
        ),
    ]
